// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: api/cdc.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_OP_UNKNOWN Operation = 0
	Operation_OP_CREATE  Operation = 1
	Operation_OP_UPDATE  Operation = 2
	Operation_OP_DELETE  Operation = 3
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "OP_UNKNOWN",
		1: "OP_CREATE",
		2: "OP_UPDATE",
		3: "OP_DELETE",
	}
	Operation_value = map[string]int32{
		"OP_UNKNOWN": 0,
		"OP_CREATE":  1,
		"OP_UPDATE":  2,
		"OP_DELETE":  3,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_api_cdc_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_api_cdc_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_api_cdc_proto_rawDescGZIP(), []int{0}
}

type Company struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Employees     int32                  `protobuf:"varint,4,opt,name=employees,proto3" json:"employees,omitempty"`
	Registered    bool                   `protobuf:"varint,5,opt,name=registered,proto3" json:"registered,omitempty"`
	CompanyType   string                 `protobuf:"bytes,6,opt,name=company_type,json=companyType,proto3" json:"company_type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_api_cdc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_api_cdc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_api_cdc_proto_rawDescGZIP(), []int{0}
}

func (x *Company) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Company) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Company) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Company) GetEmployees() int32 {
	if x != nil {
		return x.Employees
	}
	return 0
}

func (x *Company) GetRegistered() bool {
	if x != nil {
		return x.Registered
	}
	return false
}

func (x *Company) GetCompanyType() string {
	if x != nil {
		return x.CompanyType
	}
	return ""
}

func (x *Company) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Company) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CDC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Before        *Company               `protobuf:"bytes,1,opt,name=before,proto3" json:"before,omitempty"`
	After         *Company               `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
	Op            Operation              `protobuf:"varint,3,opt,name=op,proto3,enum=cdc.Operation" json:"op,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CDC) Reset() {
	*x = CDC{}
	mi := &file_api_cdc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CDC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CDC) ProtoMessage() {}

func (x *CDC) ProtoReflect() protoreflect.Message {
	mi := &file_api_cdc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CDC.ProtoReflect.Descriptor instead.
func (*CDC) Descriptor() ([]byte, []int) {
	return file_api_cdc_proto_rawDescGZIP(), []int{1}
}

func (x *CDC) GetBefore() *Company {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *CDC) GetAfter() *Company {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *CDC) GetOp() Operation {
	if x != nil {
		return x.Op
	}
	return Operation_OP_UNKNOWN
}

func (x *CDC) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_api_cdc_proto protoreflect.FileDescriptor

const file_api_cdc_proto_rawDesc = "" +
	"\n" +
	"\rapi/cdc.proto\x12\x03cdc\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x02\n" +
	"\aCompany\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1c\n" +
	"\temployees\x18\x04 \x01(\x05R\temployees\x12\x1e\n" +
	"\n" +
	"registered\x18\x05 \x01(\bR\n" +
	"registered\x12!\n" +
	"\fcompany_type\x18\x06 \x01(\tR\vcompanyType\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_description\"\xa9\x01\n" +
	"\x03CDC\x12$\n" +
	"\x06before\x18\x01 \x01(\v2\f.cdc.CompanyR\x06before\x12\"\n" +
	"\x05after\x18\x02 \x01(\v2\f.cdc.CompanyR\x05after\x12\x1e\n" +
	"\x02op\x18\x03 \x01(\x0e2\x0e.cdc.OperationR\x02op\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*H\n" +
	"\tOperation\x12\x0e\n" +
	"\n" +
	"OP_UNKNOWN\x10\x00\x12\r\n" +
	"\tOP_CREATE\x10\x01\x12\r\n" +
	"\tOP_UPDATE\x10\x02\x12\r\n" +
	"\tOP_DELETE\x10\x03B#Z!github.com/vkalekis/companies/apib\x06proto3"

var (
	file_api_cdc_proto_rawDescOnce sync.Once
	file_api_cdc_proto_rawDescData []byte
)

func file_api_cdc_proto_rawDescGZIP() []byte {
	file_api_cdc_proto_rawDescOnce.Do(func() {
		file_api_cdc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_cdc_proto_rawDesc), len(file_api_cdc_proto_rawDesc)))
	})
	return file_api_cdc_proto_rawDescData
}

var file_api_cdc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_cdc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_cdc_proto_goTypes = []any{
	(Operation)(0),                // 0: cdc.Operation
	(*Company)(nil),               // 1: cdc.Company
	(*CDC)(nil),                   // 2: cdc.CDC
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_api_cdc_proto_depIdxs = []int32{
	3, // 0: cdc.Company.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: cdc.Company.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: cdc.CDC.before:type_name -> cdc.Company
	1, // 3: cdc.CDC.after:type_name -> cdc.Company
	0, // 4: cdc.CDC.op:type_name -> cdc.Operation
	3, // 5: cdc.CDC.timestamp:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_cdc_proto_init() }
func file_api_cdc_proto_init() {
	if File_api_cdc_proto != nil {
		return
	}
	file_api_cdc_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_cdc_proto_rawDesc), len(file_api_cdc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_cdc_proto_goTypes,
		DependencyIndexes: file_api_cdc_proto_depIdxs,
		EnumInfos:         file_api_cdc_proto_enumTypes,
		MessageInfos:      file_api_cdc_proto_msgTypes,
	}.Build()
	File_api_cdc_proto = out.File
	file_api_cdc_proto_goTypes = nil
	file_api_cdc_proto_depIdxs = nil
}
